---
- name: Playbook
  hosts: central
  become: yes
  become_user: root
  tasks:
    - name: Git checkout
      register: source_code_clones
      ansible.builtin.git:
        repo: 'https://github.com/bunkorner/SPE_MiniProject.git'
        dest: /home/ubuntu/ansible
    - name: maven clean package
      command: mvn -f /home/ubuntu/ansible/pom.xml clean package
    - name: Build Docker image from Dockerfile
      docker_image:
        name: MySPE_MiniCalc
        dest: /home/ubuntu/ansible
        path: docker
        state: build