---
- name: Playbook
  hosts: central
  become: yes
  become_user: root
  tasks:
    - name: Git checkout
      register: source_code_clones
      ansible.builtin.git:
        repo: 'https://github.com/bunkorner/SPE_MiniProject.git'
        dest: /home/ubuntu/ansible
    - name: maven clean package
      command: mvn -f /home/ubuntu/ansible/pom.xml clean package
    - name: build container image
      docker_image:
        name: bunkorner/democontainer:latest
        build:
          path: /home/ubuntu/ansible
        source: build
        state: present
    - name: Tag and push to docker hub
      community.docker.docker_image:
        name: bunkorner/democontainer:latest
        repository: bunkorner/democontainer:latest
        push: true
        source: local
    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: bunkorner/democontainer
        tag: latest